const ROLES = [
  'ADMIN',
  'SUPER_ADMIN',
  'PROVINCE_ADMIN',
  'DISTRICT_ADMIN',
  'STATION_ADMIN',
  'POLICE',
];

const ADMIN_ROLES = [
  'ADMIN',
  'SUPER_ADMIN',
  'PROVINCE_ADMIN',
  'DISTRICT_ADMIN',
  'STATION_ADMIN',
];

const ALL_HUMAN_ROLES = [...ADMIN_ROLES, 'POLICE'];

const CREATE_RULES = {
  ADMIN: ['SUPER_ADMIN', 'PROVINCE_ADMIN', 'DISTRICT_ADMIN', 'STATION_ADMIN', 'POLICE'],
  SUPER_ADMIN: ['ADMIN', 'PROVINCE_ADMIN', 'DISTRICT_ADMIN', 'STATION_ADMIN', 'POLICE'],
  PROVINCE_ADMIN: ['DISTRICT_ADMIN', 'STATION_ADMIN', 'POLICE'],
  DISTRICT_ADMIN: ['STATION_ADMIN', 'POLICE'],
  STATION_ADMIN: ['POLICE'],
  POLICE: [],
};

module.exports = {
  ROLES,
  ADMIN_ROLES,
  ALL_HUMAN_ROLES,
  CREATE_RULES,
};
